#!/bin/bash

# Export Azure credentials as environment variables
export ARM_CLIENT_ID="57d60e9f-9cf7-46f7-9737-1cbd6a8318b8"
export ARM_CLIENT_SECRET="ga08Q~E5BOwfaTbN7_RGbU_Upv94sB2Y8zXXrcCo"
export ARM_SUBSCRIPTION_ID="8d42870d-3e7a-48d8-8dcf-8b20ed4c5ad6"
export ARM_TENANT_ID="995e9592-80c4-4aa3-b509-dd37e0571c05"
